"""ajout resolution incidents

Revision ID: 18312dc00efe
Revises: 
Create Date: 2026-02-03 20:25:33.014884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18312dc00efe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_resolution', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolu_par_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_incidents_resolu_par', 'user', ['resolu_par_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('resolu_par_id')
        batch_op.drop_column('date_resolution')

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('must_change_password', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
